# import = ["/home/niko/.config/alacritty/rose-pine.toml"]
# import = ["/home/niko/.config/alacritty/alacritty-ayu-dark.toml"] 
# import = ["/Users/niko/.config/alacritty/rose-pine.toml"]
general.import = ["~/.config/alacritty/alacritty-ayu-dark.toml"] 
# general.import = ["~/.config/alacritty/everforest.toml"] 

[cursor]
thickness = 0.25

[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 2

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.offset]
x = 0
y = 4

[[keyboard.bindings]]
chars = "\u0007z"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B,b"
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007\u0007"
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007p"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007n"
key = "L"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007n"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007p"
key = "P"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0007c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B/"
key = "F"
mods = "Command"

[window]
# decorations = "None"

