[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.cursor]
cursor = "#ff5289"
text = "#000000"

[colors.normal]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2d353b"
foreground = "#d3c6aa"

# [schemes.everforest_dark_hard.bright]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [schemes.everforest_dark_hard.cursor]
# cursor = "#ff5289"
# text = "#000000"
#
# [schemes.everforest_dark_hard.normal]
# black = "#414b50"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [schemes.everforest_dark_hard.primary]
# background = "#272e33"
# foreground = "#d3c6aa"
#
# [schemes.everforest_dark_medium.bright]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [schemes.everforest_dark_medium.cursor]
# cursor = "#ff5289"
# text = "#000000"
#
# [schemes.everforest_dark_medium.normal]
# black = "#475258"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [schemes.everforest_dark_medium.primary]
# background = "#2d353b"
# foreground = "#d3c6aa"
#
# [schemes.everforest_dark_soft.bright]
# black = "#4d5960"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [schemes.everforest_dark_soft.cursor]
# cursor = "#ff5289"
# text = "#000000"
#
# [schemes.everforest_dark_soft.normal]
# black = "#4d5960"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"
#
# [schemes.everforest_dark_soft.primary]
# background = "#333c43"
# foreground = "#d3c6aa"
